### ISSUE TITLE
astroid 2.0 causes ImportError: cannot import name 'CallFunc'

### ISSUE THREAD

**Issue by seanh** [landscapeio/requirements-detector#20]
I've started seeing requirements-detector crash when I run prospector, though it was working fine before:

<pre><code>tox -e lint
lint create: /home/seanh/Projects/lms/.tox/lint
lint installdeps: prospector, mock, pytest, factory-boy, -rrequirements.txt
lint installed: alembic==0.9.6,<strong>astroid==2.0</strong>,atomicwrites==1.1.5,attrs==18.1.0,certifi==2017.11.5,chardet==3.0.4,dodgy==0.1.9,factory-boy==2.11.1,Faker==0.8.17,flake8==3.5.0,flake8-polyfill==1.0.2,gunicorn==19.7.1,httplib2==0.10.3,hupper==1.0,idna==2.6,isort==4.3.4,Jinja2==2.10,lazy-object-proxy==1.3.1,Mako==1.0.7,MarkupSafe==1.0,mccabe==0.6.1,mock==2.0.0,more-itertools==4.2.0,newrelic==2.98.0.81,oauth2==1.9.0.post1,oauthlib==2.0.6,PasteDeploy==1.5.2,pbr==4.1.0,pep8-naming==0.7.0,plaster==1.0,plaster-pastedeploy==0.4.2,pluggy==0.6.0,prospector==0.12.11,psycopg2==2.7.3.2,py==1.5.4,pycodestyle==2.3.1,pycrypto==2.4,pydocstyle==2.1.1,pyflakes==1.6.0,PyJWT==1.5.3,pylint==1.9.2,pylint-common==0.2.5,pylint-plugin-utils==0.4,PyLTI==0.5.1,pyramid==1.9.1,pyramid-jinja2==2.7,pyramid-services==1.1,pyramid-tm==2.2,pytest==3.6.3,python-dateutil==2.6.1,python-editor==1.0.3,PyYAML==3.13,raven==6.4.0,repoze.lru==0.7,requests==2.18.4,requests-oauthlib==0.8.0,requirements-detector==0.5.2,setoptconf==0.2.0,six==1.11.0,snowballstemmer==1.2.1,SQLAlchemy==1.1.15,text-unidecode==1.2,transaction==2.1.2,translationstring==1.3,typed-ast==1.1.0,urllib3==1.22,venusian==1.1.0,WebOb==1.7.4,wrapt==1.10.11,zope.deprecation==4.3.0,zope.interface==4.4.3,zope.sqlalchemy==0.7.7
lint runtests: PYTHONHASHSEED='2814062973'
lint runtests: commands[0] | prospector
Traceback (most recent call last):
  File "/home/seanh/Projects/lms/.tox/lint/bin/prospector", line 7, in <module>
    from prospector.run import main
  File "/home/seanh/Projects/lms/.tox/lint/lib/python3.6/site-packages/prospector/run.py", line 9, in <module>
    from prospector.config import configuration as cfg
  File "/home/seanh/Projects/lms/.tox/lint/lib/python3.6/site-packages/prospector/config/__init__.py", line 7, in <module>
    from prospector.autodetect import autodetect_libraries
  File "/home/seanh/Projects/lms/.tox/lint/lib/python3.6/site-packages/prospector/autodetect.py", line 4, in <module>
    from requirements_detector import find_requirements
  File "/home/seanh/Projects/lms/.tox/lint/lib/python3.6/site-packages/requirements_detector/__init__.py", line 1, in <module>
    from requirements_detector.detect import find_requirements
  File "/home/seanh/Projects/lms/.tox/lint/lib/python3.6/site-packages/requirements_detector/detect.py", line 5, in <module>
    from astroid import MANAGER, CallFunc, Name, Assign, Keyword, List, Tuple, Const, AssName
ImportError: cannot import name 'CallFunc'
ERROR: InvocationError for command '/home/seanh/Projects/lms/.tox/lint/bin/prospector' (exited with code 1)</code></pre>

**Comment by seanh** [comment]
I think this has been caused by the release of Astroid 2.0:

* [`astroid==2.0` was released three days ago](https://pypi.org/project/astroid/2.0/) and it looks like it removes the name `CallFunc`
* With Python > 2.6 [requirements-detector will use the latest version of astroid](https://github.com/landscapeio/requirements-detector/blob/a73d27c6d5d1640fb83989a508a0ba027fde0172/setup.py#L34), so since three days ago it'll use astroid 2.0.
* `CallFunc` was [renamed to `Call` in Astroid 4.0](https://github.com/PyCQA/astroid/blob/7442c6a9e4250d5e2810bddfaf18f15192d70c33/ChangeLog#L797) but the old name was kept for backwards compat. I think Astroid 2.0 removes the old name.
* But [requirements-detector still uses the old name](https://github.com/landscapeio/requirements-detector/blob/05276151849d8546fd8e602e0728a9cb0574f4d2/requirements_detector/detect.py#L5)

**Comment by seanh** [comment]
(And if I pin it to astroid==1.6.5 the crash goes away)

**Comment by seanh** [comment]
Thanks!
